---
  default: &default
    :search_record_limit: 250
    :base_url: ~ # Set to `nil` to have it dynamically set at runtime.
    :email:
      :from: 'noreply@tombstone.msc.local'
      :delivery_method: !ruby/symbol sendmail
    :ldap:
      :servers:
        - 'dc01.msc.local'
        - 'dc02.msc.local'
      :domain: 'msc.local'
      :username: 'tombstone_user'
      :password: '10Pippl$ah'
    :roles:
      :operator: &operator
        :can_create: true
        :can_edit: true
        :can_delete: true
        :can_approve: false
        :can_inter: false
        :can_complete: false
        :can_delete_legacy: false
        :can_delete_provisional: true
        :can_delete_pending: true
        :can_delete_approved: false
        :can_delete_interred: false
        :can_delete_completed: false
        :can_delete_deleted: false
        :can_edit_legacy: true
        :can_edit_provisional: true
        :can_edit_pending: true
        :can_edit_approved: true
        :can_edit_interred: false
        :can_edit_completed: false
        :can_edit_deleted: false
        :can_delete_files: false
        :can_manage_cemeteries: false
      :coordinator: &coordinator
        <<: *operator
        :can_approve: true
        :can_inter: true
        :can_complete: true
        :can_delete_approved: true
        :can_delete_interred: true
        :can_delete_completed: true
        :can_edit_interred: true
        :can_edit_completed: true
        :can_delete_files: true
        :can_manage_cemeteries: true
      :admin:
        <<: *coordinator
        :can_delete_legacy: true
        :can_delete_deleted: true
        :can_edit_deleted: true
      :default:
    :db:
      :host: 'sql08.msc.local'
      :user: 'MSC\tombstone_user'
      :password: '10Pippl$ah'
      :database: 'Tombstone_Prod'
  test:
    <<: *default
    :db:
      :host: 'sql08.msc.local'
      :user: 'MSC\tombstone_user'
      :password: '10Pippl$ah'
      :database: 'Tombstone_Test'
  development:
    <<: *default
    :db:
      :host: 'sql08.msc.local'
      :user: 'MSC\tombstone_user'
      :password: '10Pippl$ah'
      :database: 'Tombstone_Dev'
  spec:
    <<: *default
    :db:
      :adapter: 'tinytds'
      :host: 'sql08.msc.local'
      :user: 'MSC\tombstone_user'
      :password: '10Pippl$ah'
      :database: 'Tombstone_Spec'
  demo:
    <<: *default
    :db:
      :host: 'localhost'
      :user: 'tombstone\tombstone'
      :password: 'Passw0rd'
      :database: 'Tombstone_Demo'
    :ldap:
      :servers:
        - 'localhost'
      :domain: 'tombstone.local'
      :username: 'tombstone'
      :password: 'Passw0rd'
